### PR TITLE
Stop try parent on HTTP STATUS 200

### PR DESCRIPTION
**Pull request by megoth**
This should solve https://github.com/solid/solid-ui/issues/78

### CODE REVIEW

**Comment by timbl** [comment]
Hmmm

**Comment by timbl** [comment]
tryParent needs to check and exit if there is no acl file atthe root of the domain, to avoid chopping the domain name off

**Comment by timbl** [comment]
https://github.com/solid/web-access-control-spec/blob/master/README.md
says 

> Failing that, move up the container hierarchy until you find a container with an existing ACL file, which has some permissions to inherit.

**Comment by TallTed** [comment]
Have to remember that "move up the container hierarchy" doesn't necessarily mean "truncate the path, solidus by solidus" as the URI's PATH element may not (though it often will) match the logical container hierarchy.  Challenge deepens as Containers identify the Members they contain, but Members don't necessarily identify their Containers.

**Comment by megoth** [comment]
This was handled in https://github.com/solid/solid-ui/pull/80, so closing this PR.

**Pull request closed without merging**
