### PR TITLE
Adding caching of user roles

### PR DESCRIPTION
**Pull request by megoth**
We do not want to spam profile and settings every time we navigate to another point in file structure (e.g. using the Folder view)

### CODE REVIEW

**Comment by megoth** [comment]
There is no explicit issue for this, but it was inspired by my research when investigating https://github.com/solid/folder-pane/issues/6.

**Comment by timbl** [comment]
What do you mean "spam"?  Spam means sending useless information to.  Do you mean "making unnecessary reads" of?   But the profile and preferences are already cached in the store.  Do you mean "avoiding unnecessary queries of the triple store"?   Is that a problem?

**Comment by megoth** [comment]
Ah yes, the use of the term spam is inaccurate - I meant it in the sense that there might be unnecessary amount of reads.

I can't remember exactly why I though this was necessary (it's one month old), but I might've simply forgotten that profile and preferences are already cached. Since that is the case, this is an unnecessary change, and I'll close this PR.

**Comment by timbl** [comment]
The cache you have there is global, and has no mechanism to be invalidated when the logged in user changes.  I suggest you add the user roles to the existing login context, which I guess in now part of the databrowser context?    And make suer that when the user logs out is is dropped.    scrapped on any non-public da
(Hmmm -- when the user logs out should the quadstore in fact be stripped of any non-public data?)

**Pull request closed without merging**
