### PR TITLE
Variously update authn.ts

### PR DESCRIPTION
**Pull request by TallTed**
* fix typos
* improve readability and English of various human-directed text blocks
* change `makeIndexIfNecesary` function to `makeIndexIfNecessary` (added missing `s`)

### CODE REVIEW

**Comment by megoth** [comment]
Could you run `npm run lint-fix` to make sure that the file is linted properly? I'll merge the PR once it's done ^_^

**Comment by TallTed** [comment]
@megoth - If that's runnable through the github website, I can definitely do it. Else, I'd need detailed instructions (including everything I need to do to bring the relevant files and tools onto my Mac).

But if you just look at [the changes made](https://github.com/solid/solid-ui/pull/175/files), you should see that none of them should trigger any lint or other errors -- as all are in comments or human-facing string contructs, with the exception of the renamed `makeIndexIfNecessary` function, which name occurs 3 times.

**Comment by megoth** [comment]
@TallTed seems to be a trailing space that's triggering the Lint error.

No worries, I'll fix it myself tomorrow and merge the changes then ^_^

**Comment by TallTed** [comment]
@megoth - Ah! Knowing the issue, made it easy to fix. Should merge fine now without lint complaint.

**Pull request merged**
