### PR TITLE
[WiP] Form generator cleanup

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
There's still quite a lot of room for improvement on variable names as well.

**Comment by michielbdejong** [comment]
Split up into src/widgets/forms/*
~/gh/solid/solid-ui $ wc -l src/widgets/forms/*
     212 src/widgets/forms/basic.ts
      47 src/widgets/forms/boolean.ts
     149 src/widgets/forms/checkbox.ts
     120 src/widgets/forms/choice.ts
      54 src/widgets/forms/classifier.ts
      37 src/widgets/forms/comment.ts
      44 src/widgets/forms/editForm.ts
      81 src/widgets/forms/fieldFunction.ts
      96 src/widgets/forms/fieldParams.ts
     117 src/widgets/forms/group.ts
     137 src/widgets/forms/index.ts
     142 src/widgets/forms/multiLineText.ts
     336 src/widgets/forms/multiple.ts
      92 src/widgets/forms/options.ts
     189 src/widgets/forms/promptForNew.ts
     347 src/widgets/forms/select.ts
    2200 total

**Comment by michielbdejong** [comment]
I'm actually not sure now how safe it is to merge this without improving test coverage and adding examples for all functions, so I think I'll have to complete the unit test coverage and example coverage after all, otherwise there might be a risk that I broke something somewhere...

**Comment by angelo-v** [comment]
@michielbdejong Are you actually still working on that? Should we convert it to a Draft PR then? Or close it?

**Pull request closed without merging**
