### PR TITLE
Add icons, clean up js, remove commented out code, add doc

### PR DESCRIPTION
**Pull request by timbl**
Sorry this is in one PR.
Tim

### CODE REVIEW

**Comment by michielbdejong** [comment]
This PR is superseded by #246, right?

**Comment by megoth** [comment]
> This PR is superseded by #246, right?

There is a bit work left (pull out some methods into a new module, participants.ts) which Sharon will do in https://github.com/solid/solid-ui/pull/233. She'll close this issue when she's done.

**Comment by michielbdejong** [comment]
@timbl what is the status of this PR now?

**Comment by angelo-v** [comment]
This seems to be an outdated branch nobody cares for anymore, so I close it

**Pull request closed without merging**
